name: Secure Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Config
        run: |
          mkdir -p public
          echo "window.config = {
            SUPABASE_URL: '${{ secrets.SUPABASE_URL }}',
            KEY: '${{ secrets.SUPABASE_ANON_KEY }}'
          };" > public/config.js
          
          # 验证文件内容（调试用）
          echo "Generated config:"
          cat public/config.js

      - name: Debug Files
        run: |
          echo "File structure:"
          find public/ -type f

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          force_orphan: true  # 确保每次都是全新部署
